"""
Django settings for docuweb project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]


INSTALLED_APPS.append("security")

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'security.middlewares.MicrosoftJWTAuthenticationMiddleware',
]

ROOT_URLCONF = 'docuweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'docuweb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = "security.User"

MICROSOFT_AUTH = {
    "CLIENT_ID": config("CLIENT_ID"),
    "CLIENT_SECRET": config("CLIENT_SECRET"),
    "TENANT_ID": config("TENANT_ID"),
    "REDIRECT_URI": f"http://localhost:8000/api/auth/callback",
    "AUTHORITY": f"https://login.microsoftonline.com/{  config("TENANT_ID") }",
    "TOKEN_URL": f"https://login.microsoftonline.com/{  config("TENANT_ID") }/oauth2/v2.0/token",
    "JWKS_URI": f"https://login.microsoftonline.com/{  config("TENANT_ID") }/discovery/v2.0/keys",
    "ISSUER": f"https://login.microsoftonline.com/{  config("TENANT_ID") }/v2.0",
    "SCOPE": f"{config("SCOPE")}",
    "FRONTEND_REDIRECT_URI": "http://localhost:3000/dashboard"
}


# Microsoft Identity Platform settings
MICROSOFT_CLIENT_ID = "<your-client-id>"
MICROSOFT_CLIENT_SECRET = "<your-client-secret>"
MICROSOFT_AUTHORITY = "https://login.microsoftonline.com/<your-tenant-id>"  # Or 'common' for multi-tenant
MICROSOFT_AUTHORIZE_URL = f"{MICROSOFT_AUTHORITY}/oauth2/v2.0/authorize"
MICROSOFT_TOKEN_URL = f"{MICROSOFT_AUTHORITY}/oauth2/v2.0/token"
MICROSOFT_USERINFO_URL = "https://graph.microsoft.com/oidc/userinfo"
MICROSOFT_LOGOUT_URL = f"{MICROSOFT_AUTHORITY}/oauth2/v2.0/logout"
MICROSOFT_REDIRECT_URI = "<your-redirect-uri>"  # e.g., https://yourapp.com/api/auth/callback

LOGIN_REDIRECT_URL = "/dashboard"
LOGIN_URL = "/"
ADMIN_EMAILS = ["admin@example.com"]  # Optional
IS_LOCAL = config("IS_LOCAL", False)
